# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0002_auto_20161005_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
