# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0003_auto_20161010_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=10)),
                ('sch', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(blank=True, max_length=30)),
                ('major', models.CharField(blank=True, max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihu.User'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
