# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0006_auto_20161011_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default=1, height_field=50, upload_to='', width_field=50),
        ),
    ]
