# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0007_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default=1, upload_to=''),
        ),
    ]
