# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0008_auto_20161125_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='.'),
        ),
    ]
